// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import Editora from '../editora';
import Livro from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  editoras: Array<Editora> = [];
  livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros;
    });
  }  

  excluir(codigo: string): void {
    this.servLivros.excluir(String(codigo)).then(async () => {
      this.livros = await this.servLivros.obterLivros();
    });
  }  

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container">
    <h1>Lista de Livros</h1>
    <table class="table table-striped">
      <thead class="table-dark bg-dark">
        <tr>
          <th>Título</th>
          <th>Resumo</th>
          <th>Editora</th>
          <th>Autores</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>
            {{ livro.titulo }}
            <button class="btn btn-danger" (click)="excluir(livro.codigo)">
              Excluir
            </button>
          </td>
          <td>{{ livro.resumo }}</td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </main>

// clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect } from 'react';
import ControleLivros from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';

function LinhaLivro(props) {
    const controleEditora = new ControleEditora();
    const nomeEditora = controleEditora.getNomeEditora(props.livro.codEditora);

    return (
        <tr>
            <td>{props.livro.titulo}
                <div>
                    <button className="btn btn-danger" onClick={() => props.excluir(props.livro.codigo)}>Excluir</button>
                </div>
            </td>
            <td>{props.livro.resumo}</td>
            <td>{nomeEditora}</td>
            <td>
                <ul>
                    {props.livro.autores.map((autor, index) => (
                        <li key={index}>{autor}</li>
                    ))}
                </ul>
            </td>
        </tr>
    );
}

export default function LivroLista() {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);
    const controleLivro = new ControleLivros();

    useEffect(() => {
        const obterLivros = async () => {
            controleLivro.obterLivros().then((livrosObtidos) => {
                setLivros(livrosObtidos);
                setCarregado(true);
            });
        };

        obterLivros();
    },[carregado]);

    const excluir = (codigoLivro) => {
        controleLivro.excluir(codigoLivro).then(() => {
            setCarregado(false);
        });
    };

    return (
        <main>
            <h1>Catálogo de Livros</h1>
            <table className='table table-striped'>
                <thead className='table-dark'>
                    <tr>
                        <th>Título</th>
                        <th>Resumo</th>
                        <th>Editora</th>
                        <th>Autores</th>
                    </tr>
                </thead>
                <tbody>
                    {carregado &&
                        livros.map((livro, index) => (
                            <LinhaLivro key={index} livro={livro} excluir={excluir} />
                        ))}
                </tbody>
            </table>
        </main>
    );
}
