// clientes/livros-next/pages/LivroLista.tsx
import Head from 'next/head';
import { Menu } from '../componentes/Menu';
import { LinhaLivro } from '../componentes/LinhaLivro';
import { useState, useEffect, SetStateAction } from 'react';
import styles from '../styles/Home.module.css';
import Livro from '../classes/modelo/Livro';
import ControleLivros from '../classes/controle/ControleLivros';
import 'bootstrap/dist/css/bootstrap.css';

const LivroLista: React.FC = () => {
  const controleLivros = new ControleLivros();
  const [livros, setLivros] = useState<Array<Livro>>([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    controleLivros.obterLivros().then((data: SetStateAction<Livro[]>) => {
      setLivros(data);
      setCarregado(true);
    });
  }, [carregado]);

  const excluir = async (codigo: string) => {
    await controleLivros.excluir(codigo).then(() => {
      setCarregado(false);
    });
  };

  return (
    <div className='container'>
      <Head>
        <title>Livro Lista</title>
      </Head>
      <main className={styles.main}>
        <h1>Lista de Livros</h1>
        <table className='table table-striped'>
          <thead className='table-dark'>
            <tr>
              <th>Título</th>
              <th>Resumo</th>
              <th>Editora</th>
              <th>Autor</th>
            </tr>
          </thead>
          <tbody>
            {carregado &&
              livros.map((livro, index) => (
                <LinhaLivro key={index} livro={livro} excluir={excluir} />
              ))}
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default LivroLista;

// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import Editora from '../editora';
import Livro from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  editoras: Array<Editora> = [];
  livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros;
    });
  }  

  excluir(codigo: string): void {
    this.servLivros.excluir(String(codigo)).then(async () => {
      this.livros = await this.servLivros.obterLivros();
    });
  }  

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container">
    <h1>Lista de Livros</h1>
    <table class="table table-striped">
      <thead class="table-dark bg-dark">
        <tr>
          <th>Título</th>
          <th>Resumo</th>
          <th>Editora</th>
          <th>Autores</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>
            {{ livro.titulo }}
            <button class="btn btn-danger" (click)="excluir(livro.codigo)">
              Excluir
            </button>
          </td>
          <td>{{ livro.resumo }}</td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </main>
