// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import Livro from '../livro';
import Editora from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  livro: Livro = new Livro('',0,'','',[]);
  autoresForm: string = '';
  editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  }
}

<main class="container">
    <h2>Dados do Livro</h2>
  
    <form (submit)="incluir()" ngNativeValidate>
      <div class="mb-3">
        <label for="titulo" class="form-label">Título:</label>
        <input type="text" class="form-control" id="titulo" required [(ngModel)]="livro.titulo" name="titulo">
      </div>
  
      <div class="mb-3">
        <label for="resumo" class="form-label">Resumo:</label>
        <textarea class="form-control" id="resumo" [(ngModel)]="livro.resumo" name="resumo"></textarea>
      </div>
  
      <div class="mb-3">
        <label for="editora" class="form-label">Editora:</label>
        <select class="form-select" id="editora" required [(ngModel)]="livro.codEditora" name="editora">
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
  
      <div class="mb-3">
        <label for="autores" class="form-label">Autores (1 por linha):</label>
        <textarea class="form-control" id="autores" [(ngModel)]="autoresForm" name="autores"></textarea>
      </div>
  
      <button type="submit" class="btn btn-primary">Cadastrar</button>
    </form>
  </main>

// clientes/livros-next/pages/LivroDados.tsx
import type { NextPage } from 'next';
import React from 'react';
import Head from 'next/head';
import { Menu } from '../componentes/Menu';
import ControleLivros from '../classes/controle/ControleLivros';
import { useState } from 'react';
import { useRouter } from 'next/router';
import styles from '../src/app/page.module.css';
import Livro from '../classes/modelo/Livro';
import 'bootstrap/dist/css/bootstrap.css';
import ControleEditora from '../classes/controle/ControleEditora';

const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora();

const LivroDados: NextPage = () => {
  const [opcoes, setOpcoes] = useState(
    controleEditora.getEditoras().map((editora) => ({
      value: editora.codEditora.toString(),
      text: editora.nome,
    }))
  );
  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(0);
  const navigate = useRouter().push;

  const tratarCombo = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const livro: Livro = {
      codigo: '',
      titulo,
      resumo,
      autores: autores.split('\n'),
      codEditora,
    };
    controleLivro.incluir(livro).then(() => {
      navigate('/LivroLista');
    });
  };

  return (
    <div className="container">
      <Head>
        <title>Livro Dados</title>
      </Head>
      <main className={styles.main}>
        <h1>Cadastro de Livro</h1>
        <form className="w-100" onSubmit={incluir}>
          <div className="mb-3">
            <label className="form-label">Título:</label>
            <input
              className="form-control"
              type="text"
              value={titulo}
              onChange={(event) => setTitulo(event.target.value)}
              required
            />
          </div>
          <div className="mb-3">
            <label className="form-label">Resumo:</label>
            <textarea
              className="form-control"
              value={resumo}
              onChange={(event) => setResumo(event.target.value)}
              required
            />
          </div>
          <div className="mb-3">
            <label className="form-label">Editora:</label>
            <select className="form-select" value={codEditora} onChange={tratarCombo}>
              {opcoes.map((opcao) => (
                <option key={opcao.value} value={opcao.value}>
                  {opcao.text}
                </option>
              ))}
            </select>
          </div>
          <div className="mb-3">
            <label className="form-label">Autores:</label>
            <textarea
              className="form-control"
              value={autores}
              onChange={(event) => setAutores(event.target.value)}
              required
            />
          </div>
          <button className="btn btn-primary mt-3" type="submit">
            Incluir
          </button>
        </form>
      </main>
    </div>
  );
};

export default LivroDados;
