// clientes/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import ControleLivros from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';
import { useNavigate } from 'react-router-dom';

export default function LivroDados() {
  const controleLivro = new ControleLivros();
  const controleEditora = new ControleEditora();

  const opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(opcoes[0].value);

  const navigate = useNavigate();

  const tratarCombo = (event) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = (event) => {
    event.preventDefault();

    const livro = {
      codigo: '',
      titulo,
      resumo,
      autores: autores.split('\n'),
      codEditora,
    };

    controleLivro.incluir(livro).then(() => {
      navigate('/');
    });
  };

  return (
    <main>
      <h1>Dados do Livro</h1>

      <form onSubmit={incluir}>
        <div className="mb-3">
          <label htmlFor="titulo" className="form-label">
            Título:
          </label>
          <input
            type="text"
            className="form-control"
            id="titulo"
            value={titulo}
            onChange={(event) => setTitulo(event.target.value)}
          />
        </div>

        <div className="mb-3">
          <label htmlFor="resumo" className="form-label">
            Resumo:
          </label>
          <textarea
            className="form-control"
            id="resumo"
            value={resumo}
            onChange={(event) => setResumo(event.target.value)}
          ></textarea>
        </div>

        <div className="mb-3">
          <label htmlFor="editora" className="form-label">
            Editora:
          </label>
          <select
            className="form-select"
            id="editora"
            value={codEditora}
            onChange={tratarCombo}
          >
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
          </select>
        </div>

        <div className="mb-3">
          <label htmlFor="autores" className="form-label">
            Autores (um por linha):
          </label>
          <textarea
            className="form-control"
            id="autores"
            value={autores}
            onChange={(event) => setAutores(event.target.value)}
          ></textarea>
        </div>

        <button type="submit" className="btn btn-primary">
          Salvar Dados
        </button>
      </form>
    </main>
  );
}

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import Livro from '../livro';
import Editora from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  livro: Livro = new Livro('',0,'','',[]);
  autoresForm: string = '';
  editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  }
}

<main class="container">
    <h2>Dados do Livro</h2>
  
    <form (submit)="incluir()" ngNativeValidate>
      <div class="mb-3">
        <label for="titulo" class="form-label">Título:</label>
        <input type="text" class="form-control" id="titulo" required [(ngModel)]="livro.titulo" name="titulo">
      </div>
  
      <div class="mb-3">
        <label for="resumo" class="form-label">Resumo:</label>
        <textarea class="form-control" id="resumo" [(ngModel)]="livro.resumo" name="resumo"></textarea>
      </div>
  
      <div class="mb-3">
        <label for="editora" class="form-label">Editora:</label>
        <select class="form-select" id="editora" required [(ngModel)]="livro.codEditora" name="editora">
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
  
      <div class="mb-3">
        <label for="autores" class="form-label">Autores (1 por linha):</label>
        <textarea class="form-control" id="autores" [(ngModel)]="autoresForm" name="autores"></textarea>
      </div>
  
      <button type="submit" class="btn btn-primary">Cadastrar</button>
    </form>
  </main>
